import type { Model, GeneratedFile } from "@/types";
import { generateModelCode, generateHandlerCode, generateRouterCode, generateCargoToml } from "./rust";
import { generateApiClient, generateHooks, generateTypes, generatePackageJson } from "./typescript";
import { generateMigration, generateDownMigration } from "./sql";
import { generateDockerfile, generateDockerCompose, generateCI, generateEnvExample } from "./docker";

export interface GenerationOptions {
  projectName: string;
  models: Model[];
  generateModels: boolean;
  generateApi: boolean;
  generateAuth: boolean;
  generateDb: boolean;
  generateConfig: boolean;
  generateTests: boolean;
  generateFrontend: boolean;
  generateDocker: boolean;
  generateReadme: boolean;
  frontendFramework: string;
}

export function generateAll(options: GenerationOptions): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Models
  if (options.generateModels) {
    for (const model of options.models) {
      files.push({
        path: `src/models/${model.name.toLowerCase()}.rs`,
        content: generateModelCode(model),
      });
    }
  }

  // API Handlers
  if (options.generateApi) {
    for (const model of options.models) {
      files.push({
        path: `src/handlers/${model.tableName}.rs`,
        content: generateHandlerCode(model),
      });
    }
    files.push({
      path: "src/routes/mod.rs",
      content: generateRouterCode(options.models),
    });
  }

  // Auth module
  if (options.generateAuth) {
    files.push({
      path: "src/auth/mod.rs",
      content: `use jsonwebtoken::{decode, encode, DecodingKey, EncodingKey, Header, Validation};\nuse serde::{Deserialize, Serialize};\n\n#[derive(Debug, Serialize, Deserialize)]\npub struct Claims {\n    pub sub: String,\n    pub exp: usize,\n    pub iat: usize,\n}\n\npub fn generate_token(secret: &str) -> String {\n    // JWT implementation\n    todo!()\n}\n`,
    });
  }

  // Database connection
  if (options.generateDb) {
    files.push({
      path: "src/db/mod.rs",
      content: `use sqlx::PgPool;\n\npub async fn create_pool(database_url: &str) -> Result<PgPool, sqlx::Error> {\n    PgPool::connect(database_url).await\n}\n`,
    });
  }

  // Migrations
  if (options.models.length > 0) {
    files.push({
      path: "migrations/001_create_tables.up.sql",
      content: generateMigration(options.models),
    });
    files.push({
      path: "migrations/001_create_tables.down.sql",
      content: generateDownMigration(options.models),
    });
  }

  // Config files
  if (options.generateConfig) {
    files.push({ path: "Cargo.toml", content: generateCargoToml(options.projectName) });
    files.push({ path: ".env.example", content: generateEnvExample() });
  }

  // Tests
  if (options.generateTests) {
    files.push({
      path: "tests/auth_test.rs",
      content: `#[tokio::test]\nasync fn test_auth_flow() {\n    // TODO: Implement auth tests\n}\n`,
    });
    files.push({
      path: "tests/api_test.rs",
      content: `#[tokio::test]\nasync fn test_api_endpoints() {\n    // TODO: Implement API tests\n}\n`,
    });
  }

  // Frontend SDK
  if (options.generateFrontend) {
    for (const model of options.models) {
      files.push({
        path: `frontend/src/api/${model.tableName}.ts`,
        content: generateApiClient(model),
      });
      files.push({
        path: `frontend/src/hooks/use${model.name}s.ts`,
        content: generateHooks(model),
      });
    }
    for (const model of options.models) {
      files.push({
        path: `frontend/src/types/${model.name}.ts`,
        content: generateTypes(model),
      });
    }
    files.push({
      path: "frontend/package.json",
      content: generatePackageJson(options.frontendFramework),
    });
  }

  // Docker
  if (options.generateDocker) {
    files.push({ path: "Dockerfile", content: generateDockerfile() });
    files.push({ path: "docker-compose.yml", content: generateDockerCompose() });
    files.push({ path: ".github/workflows/ci.yml", content: generateCI() });
  }

  // README
  if (options.generateReadme) {
    files.push({
      path: "README.md",
      content: `# ${options.projectName}\n\nGenerated by AXUMkit.\n\n## Getting Started\n\n\`\`\`bash\ncp .env.example .env\n# Edit .env with your settings\ncargo run\n\`\`\`\n\n## API Endpoints\n\n${options.models.map((m) => `- GET /api/v1/${m.tableName}`).join("\n")}\n`,
    });
  }

  // Main entry point
  files.push({
    path: "src/main.rs",
    content: `use axum::Router;\nuse std::net::SocketAddr;\n\nmod models;\nmod routes;\nmod state;\n\n#[tokio::main]\nasync fn main() {\n    tracing_subscriber::init();\n\n    let state = state::AppState::new().await;\n    let app = Router::new()\n        .nest("/api/v1", routes::create_router())\n        .with_state(state);\n\n    let addr = SocketAddr::from(([0, 0, 0, 0], 3000));\n    tracing::info!("Listening on {}", addr);\n\n    axum::Server::bind(&addr)\n        .serve(app.into_make_service())\n        .await\n        .unwrap();
}
`,
  });

  return files;
}
