import type { Model, Field, FieldType } from "@/types";

function mapFieldTypeToSQL(type: FieldType): string {
  const map: Record<FieldType, string> = {
    string: "VARCHAR(255)",
    integer: "INTEGER",
    float: "REAL",
    boolean: "BOOLEAN",
    datetime: "TIMESTAMP WITH TIME ZONE",
    uuid: "UUID",
    text: "TEXT",
    json: "JSONB",
    enum: "VARCHAR(50)",
  };
  return map[type] || "TEXT";
}

function generateColumnDef(field: Field): string {
  const parts: string[] = [`    ${field.name} ${mapFieldTypeToSQL(field.type)}`];

  if (field.primaryKey) {
    parts[0] += " PRIMARY KEY";
  }
  if (!field.nullable && !field.primaryKey) {
    parts[0] += " NOT NULL";
  }
  if (field.unique && !field.primaryKey) {
    parts[0] += " UNIQUE";
  }
  if (field.defaultValue) {
    parts[0] += ` DEFAULT '${field.defaultValue}'`;
  }

  return parts[0];
}

export function generateMigration(models: Model[]): string {
  const lines: string[] = ["-- Generated by AXUMkit", "-- Migration: Create tables", ""];

  for (const model of models) {
    lines.push(`CREATE TABLE ${model.tableName} (`);

    const columnDefs = model.fields.map(generateColumnDef);

    // Add foreign keys for belongs_to relationships
    const fkDefs = model.relationships
      .filter((r) => r.type === "belongs_to")
      .map((r) => `    ${r.foreignKey}_id UUID REFERENCES ${r.targetModel.toLowerCase()}s(id)`);

    const allDefs = [...columnDefs, ...fkDefs];
    lines.push(allDefs.join(",\n"));

    lines.push(");");
    lines.push("");

    // Add indexes
    for (const field of model.fields) {
      if (field.indexed && !field.primaryKey) {
        lines.push(
          `CREATE INDEX idx_${model.tableName}_${field.name} ON ${model.tableName}(${field.name});`
        );
      }
    }

    // Add timestamps trigger note
    if (model.timestamps) {
      lines.push(`-- Note: Add created_at/updated_at triggers for ${model.tableName}`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

export function generateDownMigration(models: Model[]): string {
  const lines: string[] = ["-- Rollback migration", ""];

  for (const model of [...models].reverse()) {
    lines.push(`DROP TABLE IF EXISTS ${model.tableName} CASCADE;`);
  }

  return lines.join("\n");
}
